config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  devise_for :users
  get '/instagram/auth' => 'users/omniauth_callbacks#instagram'
  get 'up' => 'rails/health#show', as: :rails_health_check

  root 'posts#index'
  get '/posts/fetch_instagram' => 'posts#fetch_instagram'
  delete '/posts/destroy' => 'posts#destroy'
end

app/models/application_record.rb
# frozen_string_literal: true

class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/post.rb
# frozen_string_literal: true

class Post < ApplicationRecord
  has_one_attached :image
  belongs_to :user

  def image_url
    Rails.application.routes.url_helpers.url_for image if image.attached?
  end
end

app/models/user.rb
# frozen_string_literal: true

class User < ApplicationRecord
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :posts, dependent: :destroy
end

app/controllers/application_controller.rb
# frozen_string_literal: true

class ApplicationController < ActionController::Base
end

app/controllers/posts_controller.rb
# frozen_string_literal: true

require 'open-uri'

class PostsController < ApplicationController
  def index
    return render 'posts/sign' unless current_user

    @posts = current_user.posts.order(:created_at).with_attached_image
  end

  def destroy
    current_user.posts.each do |post|
      post.image.purge
      post.destroy!
    end

    redirect_to root_path
  end

  def fetch_instagram
    return redirect_back fallback_location: root_path unless current_user.instagram_token

    client = InstagramBasicDisplay::Client.new(auth_token: current_user.instagram_token)
    media_feed = client.media_feed(fields: %i[id caption media_url media_type]).body['data']
    media_feed.each do |media|
      next if media['media_type'] == 'VIDEO'

      url = media['media_url']
      Post.find_or_create_by!(unique_id: media['id']) do |post|
        post.user = current_user
        post.caption = media['caption']
        post.source = 'instagram'
        post.image.attach(io: URI.parse(url).open, filename: File.basename(url))
      end
    end

    redirect_to root_path
  end
end

app/controllers/users/omniauth_callbacks_controller.rb
# frozen_string_literal: true

module Users
  class OmniauthCallbacksController < ApplicationController
    skip_before_action :verify_authenticity_token, only: :instagram

    def instagram
      return head :bad_request unless params[:code]

      extract_token_expired_at
      user = find_or_create_user
      sign_in user
      redirect_to root_path
    end

    private

    def extract_token_expired_at
      client = InstagramBasicDisplay::Client.new
      long_token_request = client.long_lived_token(access_code: params[:code])
      @expired_at = long_token_request.payload['expires_in'].seconds.from_now
      @token = long_token_request.payload['access_token']
    end

    def find_or_create_user
      profile = InstagramBasicDisplay::Client.new(auth_token: @token).profile
      user_instagram_id = profile.payload['id']
      User.find_or_create_by!(instagram_id: user_instagram_id) do |user|
        user.instagram_username = profile.payload['username']
        user.email = "#{user_instagram_id}@instagram.fake"
        user.password = Devise.friendly_token
        user.provider = 'instagram'
        user.instagram_token = @token
        user.instagram_token_expires_at = @expired_at
      end
    end
  end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Instagram Demo</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
  </head>

  <body>
  <%= yield %>
  </body>
</html>

app/views/posts/index.html.erb
Welcome <%= current_user.instagram_username %> !
<%= button_to "Fetch Instagram Posts", posts_fetch_instagram_path, method: :get, data: { turbo: false } %>
<%= button_to "Delete Instagram Posts", posts_destroy_path, method: :delete, data: { turbo: false } %>
<%= button_to "Sign out", destroy_user_session_path, method: :delete, data: { turbo: false } %>

<% @posts.each do |post| %>
  <div>
    <%= image_tag post.image_url, alt: post.caption, size: '250x250' %>
    <p><%= post.caption %></p>
  </div>
<% end %>

app/views/posts/sign.html.erb
<%
  instagram_sign_url = "https://api.instagram.com/oauth/authorize?" \
                        "client_id=#{ENV['INSTAGRAM_CLIENT_ID']}" \
                        "&redirect_uri=#{ENV['INSTAGRAM_REDIRECT_URI']}" \
                        "&scope=user_profile,user_media&response_type=code"
%>
<%= button_to "Sign in with Instagram", instagram_sign_url, data: { turbo: false } %>